title: MiddSafe Online Advocate
description:
baseurl: "/middsafe-online-advocate"

markdown: kramdown
exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - yarn.lock
  - README.md
  - "*.log"
